version: '3'

services:
  web:
    image: peterleonov/inshaker-web
    build: .
    ports:
      - 80:80
    volumes:
      - .:/app
      - ./nginx.production.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - storage

  storage:
    image: peterleonov/inshaker-storage
    build: ./storage
    volumes:
      - ./storage:/app
    restart: always
