version: '3'

services:
  web:
    image: peterleonov/inshaker-web
    build: .
    ports:
      - 80:80
    restart: always
    depends_on:
      - storage

  storage:
    image: peterleonov/inshaker-storage
    build: ./storage
    restart: always
