#!/usr/bin/ruby

require 'erb'

class File
  def self.write file, data
    File.open(file, 'w') do |f|
      f.write data
    end
  end
end

NGINX = "/usr/local/nginx/sbin/nginx"
APACHE = "/usr/local/apache/sbin/httpd"
DIR = $0.match(/^(.+)\//)[1]
NAME = DIR.match(/^.+\/(.+)/)[1]


if ENV['SERVER_TYPE'] == "developer"
  TYPE = "developer"
  NGINX_PORT = 8003
  APACHE_PORT = 8103
  APACHE_HOST = "localhost"
else
  TYPE = "server"
  NGINX_PORT = 80
  APACHE_PORT = 8100
  APACHE_HOST = "localhost"
end

# http://localhost:4000/act/

puts "Starting #{NAME} as #{TYPE}..."

if File.exists?("#{DIR}/nginx.pid")
  puts "  nginx is already started"
else
  ERB.new(File.read("#{DIR}/nginx.conf")).result(TOPLEVEL_BINDING.taint)
  system "#{NGINX} -c #{DIR}/nginx.conf.tmp"
end

if File.exists?("#{DIR}/nginx.pid")
  puts "  apache is already started"
else
  File.write("#{DIR}/apache.conf.tmp", ERB.new(File.read("#{DIR}/apache.conf")).result(TOPLEVEL_BINDING.taint))
  system "#{APACHE} -f #{DIR}/apache.conf.tmp"
end

