#!/bin/sh

NAME="inshaker"

PROJ_ROOT="/www/$NAME"
NGINX="/usr/local/nginx/sbin/nginx"
FCGIWRAP="/usr/bin/spawn-fcgi -P $PROJ_ROOT/act.pid -u www -a 127.0.0.1 -p 4003 /usr/bin/fcgiwrap"
TYPE="$SERVER_TYPE"

if [ "$TYPE" = "" ]; then
	TYPE="developer"
fi


echo "Starting $NAME as $TYPE..."

$NGINX -c "$PROJ_ROOT/nginx.$TYPE.conf"
$FCGIWRAP
