#!/bin/sh

PROJ_ROOT="$(cd "$(dirname "$0")" && pwd)/"

# stopping mini_httpd
PID="$PROJ_ROOT/var/mini_httpd.pid"
if [ -f "$PID" ]; then
	kill -INT $(cat "$PID")
	rm -f "$PID"
else
	echo "mini_httpd wasn't started (no pid file found)"
fi


# stopping nginx.inshaker
PID="$PROJ_ROOT/var/nginx.inshaker.pid"
if [ -f "$PID" ]; then
	kill -INT $(cat "$PID")
else
	echo "nginx wasn't started (no pid file found)"
fi
rm -f $PROJ_ROOT/var/nginx.inshaker.sock


# stopping nginx.barman
PID="$PROJ_ROOT/barman/var/nginx.barman.pid"
if [ -f "$PID" ]; then
	kill -INT $(cat "$PID")
else
	echo "nginx wasn't started (no pid file found)"
fi
rm -f $PROJ_ROOT/barman/var/nginx.barman.sock


# stopping storage/thin
PID="$PROJ_ROOT/storage/var/thin.pid"
if [ -f "$PID" ]; then
	kill -INT $(cat "$PID")
	rm -f "$PID"
else
	echo "thin wasn't started (no pid file found)"
fi
