#!/bin/sh

PROJ_ROOT="$(cd "$(dirname "$0")" && pwd)/"

# stopping nginx
PID="$PROJ_ROOT/var/nginx.inshaker.pid"
if [ -f "$PID" ]; then
	kill -INT $(cat "$PID")
else
	echo "nginx wasn't started (no pid file found)"
fi
rm -f $PROJ_ROOT/var/nginx.inshaker.sock

# stopping worker
PID="$PROJ_ROOT/var/worker.pid"
if [ -f "$PID" ]; then
	kill -INT $(cat "$PID")
	rm -f "$PID"
else
	echo "worker wasn't started (no pid file found)"
fi
