#!/bin/sh

NAME="inshaker"

PROJ_ROOT="/www/$NAME"
NGINX="/usr/local/nginx/sbin/nginx"
APACHE="/usr/local/apache/sbin/httpd"
TYPE="$SERVER_TYPE"

if [ "$TYPE" = "" ]; then
	TYPE="developer"
fi


echo "Stopping $NAME as $TYPE..."
# sending INT signal
if [ -f $PROJ_ROOT/nginx.pid ]; then
	kill -2 `cat $PROJ_ROOT/nginx.pid`
else
	echo "nginx was not started (no pid file found)"
fi

if [ -f $PROJ_ROOT/apache.pid ]; then
	kill -2 `cat $PROJ_ROOT/apache.pid`
else
	echo "apache was not started (no pid file found)"
fi