#!/usr/bin/env ruby
require 'socket'

# invoke with curl http://host:$PORT/
$port="34543"

Dir.chdir(File.dirname($PROGRAM_NAME))

server = TCPServer.new $port

loop do
  client = server.accept
  
  # render the minimal HTTP 1.0 header
  client.puts 'HTTP/1.0 200 OK'
  client.puts 'Content-Type: text/plain'
  client.puts '' # end of header
  
  # tell the client the server name
  client.puts "updating #{Socket.gethostname}"
  
  # run job in a worker
  child = fork do
    # worker doesn't need a server socket
    server.close
    
    # redirect all output to the client socket
    $stdout.reopen(client)
    $stdout.sync = true
    $stderr.reopen($stdout)
    
    # hooray! do the job
    system('./update-callback-job')
  end
  
  # avoid overusage of the service
  Process.wait child
  
  client.close
end
