#!/usr/bin/env ruby
require 'socket'

# invoke with curl http://HOST:PORT/
HOST = "127.0.0.1"
PORT = 34543

puts "Listening at #{HOST}:#{PORT}"
warn "WARNING: You better hide me behind nginx, as I'm a careless webserver!"


Dir.chdir(File.dirname($PROGRAM_NAME))

server = TCPServer.new(HOST, PORT)

loop do
  client = server.accept
  
  # render the minimal HTTP 1.0 header
  client.print "HTTP/1.0 200 OK\r\n"
  client.print "Content-Type: text/plain\r\n"
  client.print "\r\n" # end of header
  
  # tell the client the server name
  client.puts "updating #{Socket.gethostname}"
  
  # run the job in a worker
  fork do
    # worker doesn't need a server socket
    server.close
    
    # redirect all output to the client socket
    $stdout.reopen(client)
    $stdout.sync = true
    $stderr.reopen($stdout)
    
    uri = client.gets
    
    puts uri
    # hooray! do the job
    system('./update-callback-job')
  end
  
  # server doesn't need a client socket
  client.close
end
