#!/usr/bin/env ruby
require 'socket'

Dir.chdir(File.dirname($PROGRAM_NAME))

HOST = "127.0.0.1"
PORT = 34543

class PostForkingHTTPServer

  def initialize host, port
    @routes = {}
    
    @host = host
    @port = port
    
    @log = $stdout.dup
    @server = TCPServer.new(HOST, PORT)
    
    puts "Listening at #{HOST}:#{PORT}"
    warn "WARNING: You better hide me behind nginx, as I'm a careless webserver!"
  end
  
  def listen_loop
    loop do
      client = @server.accept

      # run the job in a worker
      child = fork do
        # worker doesn't need a server socket
        @server.close

        # redirect all output to the client socket
        $stdout.reopen(client)
        $stdout.sync = true
        $stderr.reopen($stdout)
        
        process_request client
        
        # never return from a child
        exit!
      end

      # be free, my boy
      Process.detach child

      # server doesn't need a client socket
      client.close
    end
  end
  
  def process_request client
    first_line = client.gets
    m = /^GET (\S+) /.match(first_line)
    unless m
      # render the minimal HTTP 1.0 header
      print "HTTP/1.0 400 Bad Request\r\n"
      print "\r\n" # end of header
      puts "This server expects only GET requests. Thank you." # end of header
      return
    end

    uri = m[1]
    @log.puts uri

    job = @routes[uri]
    unless job
      # render the minimal HTTP 1.0 header
      print "HTTP/1.0 400 Not found\r\n"
      print "\r\n" # end of header
      puts "Not found." # end of header
      return
    end
    
    # render the minimal HTTP 1.0 header
    print "HTTP/1.0 200 OK\r\n"
    print "Content-Type: text/plain\r\n"
    print "\r\n" # end of header

    # hooray! finally, do the job
    job.call
  end

  def get uri, &block
    @routes[uri] = block
  end
end

s = PostForkingHTTPServer.new(HOST, PORT)

s.get '/update-callback' do
  system('./worker-jobs/update-callback')
end

s.listen_loop
