[
{"name":"Absolut","path":"absolut"},
{"name":"Angostura","path":"angostura"},
{"name":"Antica","path":"antica"},
{"name":"Bacardi","path":"bacardi"},
{"name":"Barline","path":"barline"},
{"name":"Beefeater","path":"beefeater"},
{"name":"Black Bottle","path":"black-bottle"},
{"name":"Bombay Sapphire","path":"bombay-sapphire"},
{"name":"Coors","path":"coors"},
{"name":"De Kuyper","path":"de-kuyper"},
{"name":"Franciacorta","path":"franciacorta"},
{"name":"Frapin","path":"frapin"},
{"name":"Hakushika Ginjo Namachozo","path":"hakushika-ginjo-namachozo"},
{"name":"Malibu","path":"malibu"},
{"name":"Martini","path":"martini"},
{"name":"Monin","path":"monin"},
{"name":"Nonino","path":"nonino"},
{"name":"Olmeca","path":"olmeca"},
{"name":"Olmeca Altos","path":"olmeca-altos"},
{"name":"Pere Magloire","path":"pere-magloire"},
{"name":"Sagatiba","path":"sagatiba"},
{"name":"Simple","path":"simple"}
]